name: PR

on:
  pull_request:
    branches: [main]

jobs:
  build_and_test:
    runs-on: ubuntu-24.04

    steps:
      - name: Cache for Turbo
        uses: rharkor/caching-for-turbo@439abec0d28d21b192fa8817b744ffdf1ee5ac0d # v1.5
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: |
          npx @biomejs/biome ci exercise/ts/*
          npx turbo run check-types test
